use_frameworks!

platform :ios, '10.0'

target 'MLCommonUI_Example' do
  pod 'MLCommonUI', :path => '../'

  target 'MLCommonUI_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
