use_frameworks!

platform :ios, '10.0'

target 'MLCommonUI_Example' do
  pod 'MLCommonUI', :path => '../'

  target 'MLCommonUI_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
